# Generated by Django 3.1.5 on 2021-02-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210127_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
