# Generated by Django 3.1.5 on 2021-02-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210205_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
