# Generated by Django 3.1.5 on 2021-01-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('summary', models.TextField(verbose_name='요약')),
                ('Tag', models.CharField(max_length=128, verbose_name='태그')),
                ('img', models.ImageField(upload_to=None, verbose_name='이미지')),
                ('category', models.CharField(max_length=64, verbose_name='카테고리')),
                ('newspaper', models.CharField(max_length=128, verbose_name='신문사')),
                ('Link', models.URLField(verbose_name='원문 링크')),
                ('date', models.DateField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '기사',
                'verbose_name_plural': '기사',
                'db_table': 'article',
            },
        ),
    ]
