# Generated by Django 3.1.5 on 2021-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Link',
            field=models.URLField(max_length=300, verbose_name='원문 링크'),
        ),
    ]
