# Generated by Django 3.1.5 on 2021-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFinal',
            fields=[
                ('link', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('article_date', models.CharField(blank=True, max_length=128, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.TextField()),
                ('crawl_time', models.CharField(blank=True, max_length=128, null=True)),
                ('newspaper', models.CharField(blank=True, max_length=64, null=True)),
                ('tag', models.CharField(max_length=128, blank=True, null=True)),
            ],
            options={
                'verbose_name': '기사 최종',
                'verbose_name_plural': '기사 최종',
                'db_table': 'article_final',
            },
        ),
    ]
