# Generated by Django 3.1.5 on 2021-02-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlefinal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleFinal',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
